/* eslint-disable */ 

const ADD_MESSAGE = 'ADD_MESSAGE'
const ADD_APPLICATION = 'ADD_APPLICATION'

const UPDATE_MESSAGE = 'UPDATE_MESSAGE'

const SEND_MESSAGE = 'SEND_MESSAGE'
const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'

const SEND_APPLICATION = 'SEND_APPLICATION'
const SEND_APPLICATION_SUCCESS = 'SEND_APPLICATION_SUCCESS'